Release version 2.3.16
Source: 8b090a013746f365eefd01bcf9f6e69655317ae1

Change-Id: I8a3af7484e097a2e860ca00dcd9f009b9a8d8f24
Reviewed-on: https://gerrit.bouffalolab.com/c/release/bouffalo_sdk/+/8095
Tested-by: zrrong <zrrong@bouffalolab.com>
Reviewed-by: zrrong <zrrong@bouffalolab.com>

diff --git a/components/wireless/thread/openthread/script/test b/components/wireless/thread/openthread/script/test
--- a/components/wireless/thread/openthread/script/test
+++ b/components/wireless/thread/openthread/script/test
@@ -56,7 +56,7 @@ readonly OT_NODE_TYPE
 OT_NATIVE_IP="${OT_NATIVE_IP:-0}"
 readonly OT_NATIVE_IP
 
-THREAD_VERSION="${THREAD_VERSION:-1.3}"
+THREAD_VERSION="${THREAD_VERSION:-1.4}"
 readonly THREAD_VERSION
 
 INTER_OP="${INTER_OP:-0}"
@@ -89,6 +89,9 @@ readonly TREL
 LOCAL_OTBR_DIR=${LOCAL_OTBR_DIR:-""}
 readonly LOCAL_OTBR_DIR
 
+: "${OT_VT_USE_UNIX_SOCKET:=0}"
+export OT_VT_USE_UNIX_SOCKET
+
 build_simulation()
 {
     local version="$1"
@@ -104,10 +107,12 @@ build_simulation()
         "-DOT_MESSAGE_USE_HEAP=OFF"
         "-DOT_NETDATA_PUBLISHER=ON"
         "-DOT_PING_SENDER=ON"
+        "-DOT_PLATFORM_LOG_CRASH_DUMP=ON"
         "-DOT_REFERENCE_DEVICE=ON"
         "-DOT_SERVICE=ON"
         "-DOT_SRP_CLIENT=ON"
         "-DOT_SRP_SERVER=ON"
+        "-DOT_SRP_SERVER_FAST_START_MDOE=ON"
         "-DOT_UPTIME=ON"
         "-DOT_THREAD_VERSION=${version}"
     )
@@ -129,10 +134,28 @@ build_simulation()
         options+=("-DOT_CSL_RECEIVER=ON")
         options+=("-DOT_LINK_METRICS_INITIATOR=ON")
         options+=("-DOT_LINK_METRICS_SUBJECT=ON")
+        options+=("-DOT_LINK_METRICS_MANAGER=ON")
+        options+=("-DOT_WAKEUP_COORDINATOR=ON")
+        options+=("-DOT_WAKEUP_END_DEVICE=ON")
+    fi
+
+    if [[ ${OT_NODE_TYPE} == cli* ]]; then
+        # Only enable OT_PLATFORM_BOOTLOADER_MODE when testing cli.
+        # This is intended to test that the "reset bootloader" CLI command returns a "NotCapable" error
+
+        # Note: Setting this option to ON for all OT_NODE_TYPEs will cause the posix/expects CI check to fail.
+        #       This is because the simulation RCP will have the SPINEL_CAP_RCP_RESET_TO_BOOTLOADER capability,
+        #       causing the ot-cli POSIX app to send the reset to simulation RCP successfully instead of printing
+        #       the expected error.
+        options+=("-DOT_PLATFORM_BOOTLOADER_MODE=ON")
     fi
 
     if [[ ${ot_extra_options[*]+x} ]]; then
         options+=("${ot_extra_options[@]}")
+    fi
+
+    if [[ ${OT_NODE_TYPE} == rcp* ]]; then
+        options+=("-DOT_SIMULATION_INFRA_IF=OFF")
     fi
 
     OT_CMAKE_BUILD_DIR="${OT_BUILDDIR}/openthread-simulation-${version}" "${OT_SRCDIR}"/script/cmake-build simulation "${options[@]}"
@@ -157,11 +180,20 @@ build_simulation()
 build_posix()
 {
     local version="$1"
-    local options=("-DOT_MESSAGE_USE_HEAP=ON" "-DOT_THREAD_VERSION=${version}" "-DBUILD_TESTING=ON")
+    local options=(
+        "-DBUILD_TESTING=ON"
+        "-DOT_MESSAGE_USE_HEAP=ON"
+        "-DOT_PLATFORM_BOOTLOADER_MODE=ON"
+        "-DOT_PLATFORM_LOG_CRASH_DUMP=ON"
+        "-DOT_THREAD_VERSION=${version}"
+    )
 
     if [[ ${version} != "1.1" ]]; then
         options+=("-DOT_DUA=ON")
         options+=("-DOT_MLR=ON")
+        options+=("-DOT_LINK_METRICS_INITIATOR=ON")
+        options+=("-DOT_LINK_METRICS_SUBJECT=ON")
+        options+=("-DOT_LINK_METRICS_MANAGER=ON")
     fi
 
     if [[ ${FULL_LOGS} == 1 ]]; then
@@ -237,7 +269,7 @@ do_unit()
     do_unit_version "${THREAD_VERSION}"
 
     if [[ ${THREAD_VERSION} != "1.1" && ${INTER_OP_BBR} == 1 ]]; then
-        do_unit_version "1.3-bbr"
+        do_unit_version "1.4-bbr"
     fi
 }
 
@@ -256,7 +288,7 @@ do_cert()
     esac
 
     if [[ ${THREAD_VERSION} != "1.1" ]]; then
-        export top_builddir_1_3_bbr="${OT_BUILDDIR}/openthread-simulation-1.3-bbr"
+        export top_builddir_1_4_bbr="${OT_BUILDDIR}/openthread-simulation-1.4-bbr"
         if [[ ${INTER_OP} == "1" ]]; then
             export top_builddir_1_1="${OT_BUILDDIR}/openthread-simulation-1.1"
         fi
@@ -275,7 +307,7 @@ do_cert_suite()
     export top_srcdir="${OT_SRCDIR}"
 
     if [[ ${THREAD_VERSION} != "1.1" ]]; then
-        export top_builddir_1_3_bbr="${OT_BUILDDIR}/openthread-simulation-1.3-bbr"
+        export top_builddir_1_4_bbr="${OT_BUILDDIR}/openthread-simulation-1.4-bbr"
         if [[ ${INTER_OP} == "1" ]]; then
             export top_builddir_1_1="${OT_BUILDDIR}/openthread-simulation-1.1"
         fi
@@ -325,6 +357,7 @@ do_build_otbr_docker()
         "-DOT_UPTIME=ON"
         "-DOTBR_DNS_UPSTREAM_QUERY=ON"
         "-DOTBR_DUA_ROUTING=ON"
+        "-DOTBR_DHCP6_PD=ON"
     )
     local args=(
         "BORDER_ROUTING=${BORDER_ROUTING}"
@@ -338,6 +371,7 @@ do_build_otbr_docker()
         "REST_API=0"
         "WEB_GUI=0"
         "MDNS=${OTBR_MDNS:-mDNSResponder}"
+        "FIREWALL=${FIREWALL:-1}"
     )
 
     if [[ ${NAT64} != 1 ]]; then
@@ -377,11 +411,13 @@ do_build_otbr_docker()
         rm -rf third_party/openthread/repo
         rsync -r \
             --exclude=build \
+            --exclude=ot_testing \
+            --exclude=__pycache__ \
             "${otdir}/." \
             third_party/openthread/repo
         rm -rf .git
 
-        docker build -t "${otbr_docker_image}" -f etc/docker/Dockerfile . \
+        docker build -t "${otbr_docker_image}" -f etc/docker/test/Dockerfile . \
             "${docker_build_args[@]}" \
             --build-arg OTBR_OPTIONS="${otbr_options[*]}"
     )
@@ -476,9 +512,9 @@ ENVIRONMENTS:
     VERBOSE         1 to build or test verbosely. The default is 0.
     VIRTUAL_TIME    1 for virtual time, otherwise real time. The default value is 0 when running expect tests,
                     otherwise default value is 1.
-    THREAD_VERSION  1.1 for Thread 1.1 stack, 1.3 for Thread 1.3 stack. The default is 1.3.
-    INTER_OP        1 to build 1.1 together. Only works when THREAD_VERSION is 1.3. The default is 0.
-    INTER_OP_BBR    1 to build bbr version together. Only works when THREAD_VERSION is 1.3. The default is 1.
+    THREAD_VERSION  1.1 for Thread 1.1 stack, 1.4 for Thread 1.4 stack. The default is 1.4.
+    INTER_OP        1 to build 1.1 together. Only works when THREAD_VERSION is 1.4. The default is 0.
+    INTER_OP_BBR    1 to build bbr version together. Only works when THREAD_VERSION is 1.4. The default is 1.
 
 COMMANDS:
     clean           Clean built files to prepare for new build.
@@ -510,7 +546,7 @@ EXAMPLES:
     THREAD_VERSION=1.1 VIRTUAL_TIME=0 $0 clean build cert tests/scripts/thread-cert/Cert_5_1_01_RouterAttach.py
     THREAD_VERSION=1.1 VIRTUAL_TIME=0 $0 cert tests/scripts/thread-cert/Cert_5_1_02_ChildAddressTimeout.py
 
-    # Test Thread 1.3 with real time, use 'INTER_OP=1' when the case needs both versions.
+    # Test Thread 1.4 with real time, use 'INTER_OP=1' when the case needs both versions.
     VIRTUAL_TIME=0 $0 clean build cert tests/scripts/thread-cert/v1_2_test_enhanced_keep_alive.py
     INTER_OP=1 VIRTUAL_TIME=0 $0 clean build cert tests/scripts/thread-cert/v1_2_router_5_1_1.py
     INTER_OP=1 VIRTUAL_TIME=0 $0 clean build cert_suite tests/scripts/thread-cert/v1_2_*
@@ -617,7 +653,7 @@ envsetup()
         if [[ ${THREAD_VERSION} != "1.1" ]]; then
             export RADIO_DEVICE_1_1="${OT_BUILDDIR}/openthread-simulation-1.1/examples/apps/ncp/ot-rcp"
             export OT_CLI_PATH_1_1="${OT_BUILDDIR}/openthread-posix-1.1/src/posix/ot-cli"
-            export OT_CLI_PATH_BBR="${OT_BUILDDIR}/openthread-posix-1.3-bbr/src/posix/ot-cli"
+            export OT_CLI_PATH_BBR="${OT_BUILDDIR}/openthread-posix-1.4-bbr/src/posix/ot-cli"
         fi
     fi
 
@@ -656,12 +692,12 @@ main()
 {
     envsetup "$@"
 
-    if [[ -z ${1:-} ]]; then
+    if [[ -z ${1-} ]]; then
         print_usage 1
     fi
 
     [[ ${VIRTUAL_TIME} == 1 ]] && echo "Using virtual time" || echo "Using real time"
-    [[ ${THREAD_VERSION} != "1.1" ]] && echo "Using Thread 1.3 stack" || echo "Using Thread 1.1 stack"
+    [[ ${THREAD_VERSION} != "1.1" ]] && echo "Using Thread 1.4 stack" || echo "Using Thread 1.1 stack"
 
     while [[ $# != 0 ]]; do
         case "$1" in
@@ -674,12 +710,10 @@ main()
             cert)
                 shift
                 do_cert "$@"
-                shift $#
                 ;;
             cert_suite)
                 shift
                 do_cert_suite "$@"
-                shift $#
                 ;;
             get_thread_wireshark)
                 do_get_thread_wireshark
